# PythonによるAIプログラミング入門

## 1章 人工知能の概要

***

In [1]:
from module.beginnerAI import beginnerAI01

module = beginnerAI01()
print(module.GetData())
print(module.GetTarget())
print(module.GetImages())
module = None

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

## 2章 教師あり学習を用いた分類と回帰

***

In [5]:
from module.beginnerAI import beginnerAI02

module = beginnerAI02()
print(module.ShowRawData())
print(module.BinarizeData(10.0))
module = None

[[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
from module.beginnerAI import beginnerAI02

module = beginnerAI02()
print(module.MeanData())
print(module.StdData())
module = None

[ 3.775 -1.15  -1.3  ]
[3.12039661 6.36651396 4.0620192 ]


In [2]:
from module.beginnerAI import beginnerAI02

module = beginnerAI02()
print(module.Scaling())
module = None

[[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


In [3]:
from module.beginnerAI import beginnerAI02

module = beginnerAI02()
print(module.Normalize('l1'))
print(module.Normalize('l2'))
module = None

[[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]
[[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


In [1]:
from module.beginnerAI import beginnerAI02

module = beginnerAI02()
print(module.inputLabels)
print(module.encoder.classes_)
print(module.Transform(['green', 'red', 'black']))
print(module.InverseTransform([3, 0, 4, 1]))
module = None

['red', 'black', 'red', 'green', 'black', 'yellow', 'white']
['black' 'green' 'red' 'white' 'yellow']
[1, 2, 0]
['white', 'black', 'yellow', 'green']


In [5]:
from module.beginnerAI import beginnerAI02
import numpy

# testデータ作成
data = numpy.array([[3.1, 7.2], [4, 6.7], [2.9, 8], [5.1, 4.5], [6, 5], [5.6, 5], [3.3, 0.4], [3.9, 0.9], [2.8, 1], [0.5, 3.4], [1, 4], [0.6, 4.9]])
# labels = numpy.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])
labels = numpy.array([0, 1, 0, 1, 2, 1, 2, 3, 2, 3, 3, 3])

# 機械学習モデルの呼び出し
module = beginnerAI02()

# 学習開始
module.Fit(data, labels)

# 描画実行
module.meshStepSize = 0.5
module.visualizeClassifier()

module = None