# numpy, scipy

## ベクトル値の作成

***

In [1]:
import numpy

arr = list()
arr.append(numpy.array([10, 20, 30.]))
arr.append(numpy.zeros(5))
arr.append(numpy.ones(5))

for data in arr:
    print(data)

[10. 20. 30.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## 等差数列の作成

***

In [2]:
import numpy

arr = list()
arr.append(numpy.arange(0, 100, 20))
arr.append(numpy.linspace(0, 80, 5))

for data in arr:
    print(data)

[ 0 20 40 60 80]
[ 0. 20. 40. 60. 80.]


## ベクトルと数値の演算

***

In [4]:
import numpy

arr = numpy.array([1,2,3,5,8])
print(arr)
print(arr + 10)
print(arr - 10)
print(arr * 2)
print(arr / 2)
print(arr % 2)

[1 2 3 5 8]
[11 12 13 15 18]
[-9 -8 -7 -5 -2]
[ 2  4  6 10 16]
[0.5 1.  1.5 2.5 4. ]
[1 0 1 1 0]


## ベクトル同士の演算

***

In [3]:
import numpy

arr = list()
arr.append(numpy.array([1, 2, 3, 5]))
arr.append(numpy.array([8, 13, 21, 34]))
print(arr[1] + arr[0])
print(arr[1] - arr[0])
print(arr[1] * arr[0])
print(arr[1] / arr[0])
print(arr[1] % arr[0])

[ 9 15 24 39]
[ 7 11 18 29]
[  8  26  63 170]
[8.  6.5 7.  6.8]
[0 1 0 4]


## 行列の作成

***

In [ ]:
import numpy



## 単位行列の作成

***

In [ ]:
import numpy



## 非正方の単位行列

***

In [ ]:
import numpy



## その他の対角行列

***

In [ ]:
import numpy



## ベクトルから行列への変換

***

In [ ]:
import numpy



## 転置

***

In [ ]:
import numpy



## ベクトルの結合

***

In [ ]:
import numpy



## ベクトルの内積・外積

***

In [ ]:
import numpy



## 行列の四則演算

***

In [ ]:
import numpy



## 行列の積

***

In [ ]:
import numpy



## 行列の結合

***

In [ ]:
import numpy



## 行列の分割

***

In [ ]:
import numpy



## 総和

***

In [ ]:
import numpy



## 最大値・最小値

***

In [ ]:
import numpy



## 統計計算

***

In [ ]:
import numpy



## linalg

***

In [ ]:
import numpy



## 逆行列と行列式

***

In [ ]:
import numpy



## データ読み込み

***

In [ ]:
import numpy



## load・save

***

In [ ]:
import numpy



## ソート

***

In [ ]:
import numpy



## ビュー・スライス

***

In [ ]:
import numpy

